version: '3'

services:
  book-catalog:
    image: chunyiwang/book-catalog:4
    container_name: book-catalog
    networks:
      private_network:
        ipv4_address: 172.18.0.2
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://sit722_project_part3_user:3Z3E97gt3LVjjauWBVuliOmTBbBeEMjI@dpg-cr8lbiij1k6c73f4dtog-a.singapore-postgres.render.com/sit722_project_part3

  inventory:
    image: chunyiwang/inventory:2
    container_name: inventory
    networks:
      private_network:
        ipv4_address: 172.18.0.3
    ports:
      - "81:80"
    environment:
      - DATABASE_URL=postgresql://sit722_project_part3_user:3Z3E97gt3LVjjauWBVuliOmTBbBeEMjI@dpg-cr8lbiij1k6c73f4dtog-a.singapore-postgres.render.com/sit722_project_part3

networks:
  private_network:
    ipam:
      config:
        - subnet: 172.18.0.0/24

